name: traced_cache_manager
description: CacheManager implementation that integrates with Firebase Performance Monitoring to automatically record traces for network requests.
version: 1.1.0
homepage: https://pub.dev/packages/traced_cache_manager
repository: https://github.com/nareddyt/traced_cache_manager
issue_tracker: https://github.com/nareddyt/traced_cache_manager/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.4
  flutter_cache_manager: ^3.1.3
  firebase_performance: ^0.7.1+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
